// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using PoliceDataIngest.Context;

#nullable disable

namespace PoliceDataIngest.Migrations
{
    [DbContext(typeof(PoliceDbContext))]
    [Migration("20250818090054_new columns")]
    partial class newcolumns
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("PoliceDataIngest.Model.CrimeArea", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<long>("AntiSocial")
                        .HasColumnType("bigint")
                        .HasColumnName("anti_social");

                    b.Property<long>("BicycleTheft")
                        .HasColumnType("bigint")
                        .HasColumnName("bicycle_theft");

                    b.Property<long>("Burglary")
                        .HasColumnType("bigint")
                        .HasColumnName("burglary");

                    b.Property<long>("Damage")
                        .HasColumnType("bigint")
                        .HasColumnName("damage");

                    b.Property<DateTime>("Date")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("date");

                    b.Property<long>("Drugs")
                        .HasColumnType("bigint")
                        .HasColumnName("drugs");

                    b.Property<long>("H3")
                        .HasColumnType("bigint")
                        .HasColumnName("h3");

                    b.Property<long>("PersonalTheft")
                        .HasColumnType("bigint")
                        .HasColumnName("personal_theft");

                    b.Property<long>("Robbery")
                        .HasColumnType("bigint")
                        .HasColumnName("robbery");

                    b.Property<long>("Shoplifting")
                        .HasColumnType("bigint")
                        .HasColumnName("shoplifting");

                    b.Property<long>("VehicleCrime")
                        .HasColumnType("bigint")
                        .HasColumnName("vehicle_crime");

                    b.Property<long>("Violent")
                        .HasColumnType("bigint")
                        .HasColumnName("violent");

                    b.Property<long>("WeaponCrime")
                        .HasColumnType("bigint")
                        .HasColumnName("weapon_crime");

                    b.HasKey("Id");

                    b.ToTable("crime_areas");
                });
#pragma warning restore 612, 618
        }
    }
}
