// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using PoliceDataIngest.Context;

#nullable disable

namespace PoliceDataIngest.Migrations
{
    [DbContext(typeof(PoliceDbContext))]
    [Migration("20250820140926_population areas")]
    partial class populationareas
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("PoliceDataIngest.Model.CrimeArea", b =>
                {
                    b.Property<DateTime>("Date")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("date");

                    b.Property<long>("H3")
                        .HasColumnType("bigint")
                        .HasColumnName("h3");

                    b.Property<int>("AntiSocial")
                        .HasColumnType("int")
                        .HasColumnName("anti_social");

                    b.Property<int>("BicycleTheft")
                        .HasColumnType("int")
                        .HasColumnName("bicycle_theft");

                    b.Property<int>("Burglary")
                        .HasColumnType("int")
                        .HasColumnName("burglary");

                    b.Property<int>("Damage")
                        .HasColumnType("int")
                        .HasColumnName("damage");

                    b.Property<int>("Drugs")
                        .HasColumnType("int")
                        .HasColumnName("drugs");

                    b.Property<int>("PersonalTheft")
                        .HasColumnType("int")
                        .HasColumnName("personal_theft");

                    b.Property<int>("Robbery")
                        .HasColumnType("int")
                        .HasColumnName("robbery");

                    b.Property<int>("Shoplifting")
                        .HasColumnType("int")
                        .HasColumnName("shoplifting");

                    b.Property<int>("VehicleCrime")
                        .HasColumnType("int")
                        .HasColumnName("vehicle_crime");

                    b.Property<int>("Violent")
                        .HasColumnType("int")
                        .HasColumnName("violent");

                    b.Property<int>("WeaponCrime")
                        .HasColumnType("int")
                        .HasColumnName("weapon_crime");

                    b.HasKey("Date", "H3");

                    b.ToTable("crime_areas");
                });

            modelBuilder.Entity("PoliceDataIngest.Model.PopulationArea", b =>
                {
                    b.Property<long>("H3")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("h3");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("H3"));

                    b.Property<double>("Population")
                        .HasColumnType("double precision")
                        .HasColumnName("population");

                    b.HasKey("H3");

                    b.ToTable("pop_areas");
                });
#pragma warning restore 612, 618
        }
    }
}
